<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pil_jam_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pil_jam_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $jam = $this->Pil_jam_model->get_all();

        $data = array(
            'pil_jam_admin_data' => $jam,
        );
        $this->load->view('admin/layouts/header');
        $this->load->view('admin/pil_jam/pil_jam_list', $data);
        $this->load->view('admin/layouts/footer');
        // $this->load->view('pil_jam_admin/pil_jam_list', $data);
    }

    public function read($id)
    {
        $row = $this->Pil_jam_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'pilihan_jam' => $row->pilihan_jam,
            );
            $this->load->view('admin/layouts/header');
            $this->load->view('admin/pil_jam/pil_jam_read', $data);
            $this->load->view('admin/layouts/footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pil_jam_admin'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pil_jam_admin/create_action'),
            'id' => set_value('id'),
            'jam_mulai' => set_value('jam_mulai'),
            'jam_selesai' => set_value('jam_selesai'),
        );
        $this->load->view('admin/layouts/header');
        $this->load->view('admin/pil_jam/pil_jam_form', $data);
        $this->load->view('admin/layouts/footer');
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'jam_mulai' => $this->input->post('jam_mulai', TRUE),
                'jam_selesai' => $this->input->post('jam_selesai', TRUE),
            );

            $this->Pil_jam_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pil_jam_admin'));
        }
    }

    public function update($id)
    {
        $row = $this->Pil_jam_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pil_jam_admin/update_action'),
                'id' => set_value('id', $row->id),
                'jam_mulai' => set_value('jam_mulai', $row->jam_mulai),
                'jam_selesai' => set_value('jam_selesai', $row->jam_selesai),
            );
            $this->load->view('admin/layouts/header');
            $this->load->view('admin/pil_jam/pil_jam_form', $data);
            $this->load->view('admin/layouts/footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pil_jam_admin'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'jam_mulai' => $this->input->post('jam_mulai', TRUE),
                'jam_selesai' => $this->input->post('jam_selesai', TRUE),
            );

            $this->Pil_jam_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pil_jam_admin'));
        }
    }

    public function delete($id)
    {
        $row = $this->Pil_jam_model->get_by_id($id);

        if ($row) {
            $this->Pil_jam_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pil_jam_admin'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pil_jam_admin'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('jam_mulai', 'Jam mulai', 'trim|required');
        $this->form_validation->set_rules('jam_selesai', 'Jam selesai', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Pil_jam_admin.php */
/* Location: ./application/controllers/Pil_jam_admin.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-05-16 07:42:05 */
/* http://harviacode.com */
